# Generated by Django 3.0.4 on 2020-04-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('rollnumber', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_register.div')),
            ],
        ),
    ]
